# Generated by Django 5.1.4 on 2025-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_excle_model_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excle_model',
            name='file',
            field=models.FileField(upload_to='media/excel_files/'),
        ),
    ]
