# Generated by Django 5.1.4 on 2025-01-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chart_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=15)),
                ('semester', models.CharField(max_length=70)),
                ('year', models.CharField(max_length=10)),
                ('cgpa', models.FloatField(max_length=10, null=True)),
                ('recount', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
