# Generated by Django 5.1.4 on 2025-01-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_chart_data_recount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_data',
            name='cgpa',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
