# Generated by Django 5.1.4 on 2025-01-31 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_chart_data_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_data',
            name='branch',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
