# Generated by Django 5.1.4 on 2025-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
            ],
        ),
    ]
