# Generated by Django 5.1.4 on 2025-01-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image_data',
            new_name='form_data',
        ),
    ]
