# Generated by Django 5.1.4 on 2025-01-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_rename_image_data_form_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_data',
            name='name',
        ),
    ]
