# Generated by Django 5.1.4 on 2025-01-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_remove_form_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
