# Generated by Django 5.1.4 on 2025-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_alter_form_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='trail_json',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('result', models.JSONField()),
            ],
        ),
    ]
