# Generated by Django 5.1.4 on 2025-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0012_form_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='captcha',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
